apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: utils
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/vehagn/homelab'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'torrent'
      server: '*'
    - namespace: 'unpoller'
      server: '*'
    - namespace: 'unrar'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
