apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
    - { name: internal, namespace: gateway }
  hostnames: [ argocd.stonegarden.dev ]
  rules:
    - backendRefs: [ { name: argocd-server, port: 443 } ]
      matches:
        - headers: [ { name: Content-Type, value: application/grpc } ]
