apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - grpc-route.yaml
  - tls-route.yaml
  - oidc.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 8.1.3
    releaseName: "argocd"
    namespace: argocd
    valuesFile: values.yaml
