apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: grafana-sc-datasources
          env:
            - name: REQ_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: grafana-admin-credentials
                  $patch: replace
            - name: REQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: grafana-admin-credentials
                  $patch: replace
