apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: plex
spec:
  storageClassName: proxmox-csi
  volumeName: pv-plex-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12G
