apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: agent-config
    namespace: netbird
    literals:
      - NB_HOSTNAME="talos-agent"
      - NB_LOG_LEVEL="info"
      - NB_MANAGEMENT_URL="https://netbird.stonegarden.dev"
      - NB_ADMIN_URL="https://netbird.stonegarden.dev"

resources:
  - agent-setup-key.yaml
  - daemon-set.yaml
