apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jwk-rsa
  namespace: authelia
spec:
  dnsNames:
    - authelia.stonegarden.dev
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  secretName: jwk-rsa
  usages:
    - digital signature
    - key encipherment
