apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lldap-credentials
  namespace: authelia
spec:
  encryptedData:
    password: AgCFubMvDwJwG2hf8GkvYXvYdrHDqjKvqxIuf4VsFkZ4FX4v9aPjDWrbiqjdK7O8szfM3rsYa4CLIL/e30oNFkykjKUW/UvoeOCJIZFh7y4UviMbA2INsdwsZr1wAXy+/THA4dx17DndoJGE95p5mk+qaC4CJAQEBL0JEkYrqXICwsaqBEJ4A3nJyk6y6/0g5s8VIskeUGXaHa7Xt/tVLh1qCZncJtoJJDIvJgLxVXWf+VgwXcozIekNNV8g6iZT+lClTE0MN9rmKMZc2mantCMJh2gHsj9+SZQOeiZMcKghGHxRod/wBVbUVQGyOFJdthBFWUETuhpKh45G5VBPXV91fcWsbBpPYzreuu76RqtX1hGHvdZxIepvF3aj7Nxj+gq1IxBaUXeCJvNZsLJdY1RlAv4T5Yw8veLeThig1bh02rhocjRHY2HRh2ArtMEtW6gkE0GbWwrMv5lZHDKcu1pRwoT4Yo//iIkge6EkvHZWOiETOjCpKBgedYbJWOQkdr0341tfOUded9bkPm1ZOtuUMAJkF+4QeJWxzwQ37KSZsezGIeq7nQBrXja0MdOPJNi2mtkTaPZ3yyE2Jt6jfiVaZ8htoqrKcoe9sgnPL5gsaUBrgv9aVNUScC1jQcWjtYdAyn7khT17Faw163m7v8N97AeMlsqGwcgdULrrQXm21xsFTb6SJTi3HpERasINVp4P0E2aJpi1ZK0AZXf4OTdp7kC9bZopQqzx8jDzicJudg==
  template:
    metadata:
      name: lldap-credentials
      namespace: authelia
