apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-credentials
  namespace: authelia
spec:
  encryptedData:
    password: AgAHXSnsiZu9pG5QJUkSpQfuXaqDazQVQNe11rvEqVGKlAPk/Ceo2HU0bHb6F/f3tOcv9m+taYWHgVs7NI4D6XEHoNfgdd7GzJXk6dq5NyAKasmiN5M811ibPFPSqkSJ04S7iQfTONrCfjuoVPP4H6IVfh0RVGZc2DQiOwvofKAKhfAwv3FbAs2UoQdgz2sXsEKeKDrQWxFA9vcUt6yM15CWxew/WbfHHrzI2qrqvuMm5Ep0mUVyW/QCeNjeUrWUTyh0ViuXxxkp39HuCxZvpoFfTwfo+5a4eTRN2ud3baHZH8GvmoOC7Sp93cLX4FJWT6LAQo7LeFtCRKAKKxgQQcdzmZYJ9rTEXT+hcmLYajtAdLxWQvDj2ICNVZgQmJi6imDnoObTrTbYSHNZAiXhasclPsEFiY9Mg5NUcsD8X4z1zEYWpNqyozKe0hXjverYxVRZeCXuv3Og/7WCi0of/GLOcAmIl6+hvk8k+UwpO6VvsGmYAZkG6ZWILkb9qXVYcLR/iqpLZfo63/QYQUvt1VTI3An5rrIEEuY8rlBToua1lyPWLEcjR/iNzc/Hpf31fqPVT1Li1M6uqvvpu2zDySzxV8RWVtJZswJ+31lrfqOzyGuRjeBEMIrANilE+Wuw2F0OJOrsK19g1Z8qGzvvDWjLaA3bbHUrMIYCUnYSlCCszzhTl5Lw0i+3o2ySUnKVRB6Vegm3m9y3sMlMvBcjog5o5k8vCEw6rHJLqnuJpZvArShN6iA4
  template:
    metadata:
      name: smtp-credentials
      namespace: authelia
