---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: smtp-credentials
  namespace: authelia
spec:
  encryptedData:
    password: AgDcAgBgEhD8/ib/vXAjHkgFQ1o0bQrnJ0cJkLsr+RJMql0dfOC0SDjuy4Bid+UZnR44BlIezVzrJL4zQ/Us1mm3yUedeQrx37mQDnQIgArxWl2JMJZbwNcTK+3O9KosypFrUrEUKiCQW6gPuPBTJ7Px3AT+NxZo39DBOitok2CLcpWEC3JjMYrNxN/5L9mPWKL51GplDnDQHOvSIUEj2JrqcVtzsApZm0c9+xi2r90ujuNqdRFtAjXRkVFERV/i2ZbESzaVTdgcpYub6+T5kYEaRa8tDQvHPdYtYPqDyGynUPZEE44OYaoXBY5UCl4FZUWZgeCx44+5xwUlCDLvBcAF/x+1VHxEchkX/UMTQjeinks8tfIja42p+Vf8rfWd0rw0tcywwvJDlKcVKyMC+hPUmigwdXCSS+ziRku4Mo3AzZjcMaJFsmW3FHA7GRYPzCD9G1x989P9bwyJx5MvqY8uxf/i4YRHhVOuvV2QMEjbOBRgKFbXEG8nVv/SgVUxBrGVbtU+GEAIZYsUSrCrHvd2LJ/n66HV1Finu5etM0zvAepgWIGAn0YUtEqUEDTYOMq9eJiHx1KRcU+k1yzbx3NYkjGBkGhN91eumIq/fWlu4zSWAp5RyzhdMY5nls5kN9f+2UJv0nI9u8fMy2yPRvh28oW5j+SA6pNLCBIBp7qbK/SoQA6l5Yqdz9wLRS3FPAkMzwUnRT2JdZM2RHbze+4Fj5XY1wgb64uo0SAX08bXucUPqeN4Qak43EWCWc/NlIsu06KUo25sWMI0ZO21CMUycQlWGrSN1GwlITjiIQwQGv10ZJ+r88pjRLo=
  template:
    metadata:
      creationTimestamp: null
      name: smtp-credentials
      namespace: authelia
