apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-grafana
  namespace: authelia
spec:
  encryptedData:
    clientSecret: AgCafFCQXtfqrnqC0Wbeuso1WW4IyutCmKLY9q4yewHGAahBDLhVqsDDV3mMrX81JSd9Y95rA5UnUUWjWmivKORoMrLimCl9DEJBy8r5VMhu09a9GXQtp0wy09N3X3sXBRwu9OKx8Koaj1aZoXTWMrAJLOiV5V17muukGbq+oIUg62FnOCPQIbfufdxWwvhLK5MSNcJrHun1Yl8Lc5ovlr6rq349Grl2dNnu05nz7SZ3NhwjoZTumCejVbuSi3hVhpbCM3Va507NoqKxx0hb2XfvG0PAP43RDuSX8IkKWa9spkbkIDbiJVidoF6sKtYp+Wth35uFHpL30evnRm9cC8U1uxTrkgZF+D2VK2/9UkXbvTwb1N7gpop6dCkhQb+M1PiG+dLtTX1oplILP2iZXX47Rd9hdCPC5PRwCrmuasjrDb6Jlxa0ZfjgGlpgwLsX4Z1jO+WBG4i3stYr/I4/IOjex3gxDBSYuMr4MiC0/Is0HDjeScvdO7LY+tglWlxtZFdytrV1cqMRdIKGYqNeOULea74vcoxOEWtpNtRyejimZ8iWvlaYcg8z45nYZ1RTFb2AS5EfKzzNjlJWuh1ULuoTZ5DMjRrauaJ16wH+TCt7KfKvTiCTs6jag7yN6RWUHj1m/+keA6ZMaoXcSDC/iivY21vPox9YzsKXAhfrx8AcY5Nsy7roKsJ6nvHjII/SCuWZhz/aVOF4uCsPg1tOJe1Dev3TkG+sCsatNsWHieyK2bxbw/IImN11JmAjaRpRbS5IgYPz8ZOKM5A06W9QjG5HhdEYM341vsBmx0IJSNqffo7Qk7Zt6NowXAT/T401EMYSKEU22ALu0RVFW4M7/g02tOXXinxV9k0+kVQq0fh65qcZFQ==
  template:
    metadata:
      name: client-grafana
      namespace: authelia
