name: Tofu format

on:
  push:
    branches: [ '**', '!renovate/**' ]
    paths:
      - '**.tf'
      - '**.tofu'
      - '**.tfvars'
      - '**.tftpl'
  pull_request:
    types: [ opened, synchronize ]
    branches: [ '**' ]
    paths:
      - '**.tf'
      - '**.tofu'
      - '**.tfvars'
      - '**.tftpl'

jobs:
  tofu-format:
    name: run tofu format
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Tofu format
        uses: docker://ghcr.io/vehagn/homelab-devcontainer
        with:
          args: tofu fmt -recursive -diff -check
